# clone down repository with sub-modules and then build the Dockerfile to run all the tools against the code

name: Example CI SAST
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build Dockerfile
        run: docker build -t example-ci-sast:latest --rm .
      - name: Run Dockerfile
        run: docker run --rm -it -v "${PWD}":/app -w /app example-ci-sast:lastest
